name: StaffUI
author: Ameer4Real
main: Ameer4Real\StaffUI
version: 1.0
description: UI used just for staff
api: [3.0.0]
commands:
    staff:
        default: true
        description: List of all staff
